[messages]
broadcast = "&6&lRT &7&l>> &f%message%"
broadcast-invalid = "&cInvalid usage, try /gbc <message>"
find = "&a%player% is on %server%"
find-invalid = "&cInvalid usage, try /find <player>"
find-not-online = "&c%player% is not online!"
send = "&aSent %player% to %server%"
send-invalid = "&cInvalid usage, try /send <player> <server>"
send-not-online = "&c%player% is not online!"
send-not-server = "&c%server% is not a valid server!"
sendall = "&aSent all players to %server%"
sendall-invalid = "&cInvalid usage, try /sendall <server>"
sendall-not-server = "&c%server% is not a valid server!"
staffchat = "&6&lSC &7&l>> &f%player%&7: &f%message%"
staffchat-invalid = "&cInvalid usage, try /sc <message>"
staffchat-toggle-on = "&aStaffChat toggled on!"
staffchat-toggle-off = "&"
tp-invalid = "&cInvalid usage, try /gtp <player>"
tp-not-online = "&c%player% is not online!"
reload = "&aConfig files reloaded!"